// Rider-Waite-Smith tarot images (public domain, hosted on Wikimedia Commons)
export const TAROT_IMAGES: Record<string, string> = {
  "El Loco": "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg",
  "El Mago": "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
  "La Sacerdotisa": "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
  "La Emperatriz": "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
  "El Emperador": "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
  "El Hierofante": "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
  "Los Enamorados": "https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg",
  "El Carro": "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
  "La Fuerza": "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg",
  "El Ermitaño": "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg",
  "La Rueda de la Fortuna": "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
  "La Justicia": "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
  "El Colgado": "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
  "La Muerte": "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg",
  "La Templanza": "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg",
  "El Diablo": "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg",
  "La Torre": "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg",
  "La Estrella": "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg",
  "La Luna": "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg",
  "El Sol": "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg",
  "El Juicio": "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg",
  "El Mundo": "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg",
  // Minor Arcana (Rider-Waite-Smith) — via Wikimedia Special:FilePath stable URLs
  "As de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands01.jpg",
  "Dos de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands02.jpg",
  "Tres de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands03.jpg",
  "Cuatro de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands04.jpg",
  "Cinco de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands05.jpg",
  "Seis de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands06.jpg",
  "Siete de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands07.jpg",
  "Ocho de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands08.jpg",
  "Nueve de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands09.jpg",
  "Diez de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands10.jpg",
  "Sota de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands11.jpg",
  "Caballero de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands12.jpg",
  "Reina de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands13.jpg",
  "Rey de Bastos": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands14.jpg",
  "As de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups01.jpg",
  "Dos de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups02.jpg",
  "Tres de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups03.jpg",
  "Cuatro de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups04.jpg",
  "Cinco de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups05.jpg",
  "Seis de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups06.jpg",
  "Siete de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups07.jpg",
  "Ocho de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups08.jpg",
  "Nueve de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups09.jpg",
  "Diez de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups10.jpg",
  "Sota de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups11.jpg",
  "Caballero de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups12.jpg",
  "Reina de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups13.jpg",
  "Rey de Copas": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups14.jpg",
  "As de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords01.jpg",
  "Dos de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords02.jpg",
  "Tres de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords03.jpg",
  "Cuatro de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords04.jpg",
  "Cinco de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords05.jpg",
  "Seis de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords06.jpg",
  "Siete de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords07.jpg",
  "Ocho de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords08.jpg",
  "Nueve de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords09.jpg",
  "Diez de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords10.jpg",
  "Sota de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords11.jpg",
  "Caballero de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords12.jpg",
  "Reina de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords13.jpg",
  "Rey de Espadas": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords14.jpg",
  "As de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents01.jpg",
  "Dos de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents02.jpg",
  "Tres de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents03.jpg",
  "Cuatro de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents04.jpg",
  "Cinco de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents05.jpg",
  "Seis de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents06.jpg",
  "Siete de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents07.jpg",
  "Ocho de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents08.jpg",
  "Nueve de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents09.jpg",
  "Diez de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents10.jpg",
  "Sota de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents11.jpg",
  "Caballero de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents12.jpg",
  "Reina de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents13.jpg",
  "Rey de Oros": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents14.jpg",
};

export const getTarotImage = (name: string): string | undefined => {
  if (!name) return undefined;
  if (TAROT_IMAGES[name]) return TAROT_IMAGES[name];
  // Try case-insensitive match
  const key = Object.keys(TAROT_IMAGES).find(
    k => k.toLowerCase() === name.toLowerCase().trim()
  );
  return key ? TAROT_IMAGES[key] : undefined;
};
